### ISSUE TITLE
Bug in Get-DesktopIndex

### ISSUE THREAD

**Issue by jjrossi** [MScholtes/PSVirtualDesktop#11] opened 2021-01-26 13:34 UTC
When calling `Get-DesktopIndex` without arguments, the current desktop index should be returned, instead we get an error message.  To fix this, the body of the first condition should be changed from:

`$Desktop = [VirtualDesktop.Desktop]::FromDesktop(([VirtualDesktop.Desktop]::Current))`
To:
`$Desktop = [VirtualDesktop.Desktop]::Current`

I just stared looking at PS yesterday, so take this with a gain of salt.

**Comment by MScholtes** [comment] 2021-01-27 12:27
Hello jjrossi,

thanks for the advice, I will correct this issue and add a similiar step to _Get-DesktopName_.

This might take some time because of lockdown and childcare.

Greetings

Markus

**Comment by TheRancid** [comment] 2021-02-27 11:37
Hi,
while you're at it, may I also add that the `Get-DesktopIndex` function, when passed a string (desktop name part) as input, doesn't really return an integer, but a desktop object?

This command, for example:
```
New-Desktop | Set-DesktopName -Name "NewDesktop"

Get-DesktopIndex -Desktop "NewDesktop"
```

returns this:
```
IsVisible Left                   Right
--------- ----                   -----
    False VirtualDesktop.Desktop
```

Maybe the problem is in the following statement of the `Get-DesktopIndex` function (line 1230), which actually returns a desktop object?

```
return [VirtualDesktop.Desktop]::FromIndex($TempIndex)
```

Let me know if I should open a different bug, didn't want to hijack this thread...

Thanks for your great work BTW!
Best regards

**Comment by MScholtes** [comment] 2021-02-27 15:24
OK,

i will try to free up time to work on these issues in the next days.

Greetings

Markus

**Comment by MScholtes** [comment] 2021-02-28 12:00
Hello jjrossi, hello TheRancid,

I checked in the new version of **_Virtualdesktop_** today which has the errors fixed.

It took some time, as I hardly have any time on the computer (due to childcare) because of the Corona crisis. I apologise for this.

Greetings

Markus

**Comment by TheRancid** [comment] 2021-02-28 17:45
Hi,
no need to apologize, you've been blazing fast!
I've downloaded right now the updated version 1.3.1 and can confirm that the `Get-DesktopIndex` function is working correctly.

Many thanks!

Best regards

**Comment by MScholtes** [comment] 2021-03-18 11:10
Closing the issue, since it has been resolved and there is no reaction from the original issuer.

**Closed by MScholtes** 2021-03-18 11:10 UTC
